import { useEffect, useMemo, useState } from 'react'
import { RankedBar, type ChartDatum } from '../charts/ChartKit'
import { guidedQuestionById, guidedQuestions, type PlanTier } from '../content/guided-questions'
import { decodeQueryState, type SemanticDSL, useSemanticQuery } from '../lib/semantic'
import { track } from '../lib/track'
import { AskFollowUp } from './AskFollowUp'
import { SmartFilters } from './Phase2Pages'

function resultData(rows: Array<Record<string, unknown>> = []): ChartDatum[] { return rows.filter(row => row.value !== null).map((row, index) => ({ name: String(row.company ?? row.sector ?? row.mcap_band ?? row.fy ?? `Cohort ${index + 1}`), value: Number(row.value) })) }

function cohortLabel(dsl: SemanticDSL): string {
  const fy = dsl.filters.find(item => item.dimension === 'fy')?.value
  const filters = dsl.filters.filter(item => item.dimension !== 'fy').map(item => `${item.dimension.replaceAll('_', ' ')}: ${String(item.value)}`)
  const year = Array.isArray(fy) ? `FY ${fy.join('–')}` : fy ? `FY ${fy}` : 'All available years'
  return [year, ...filters, dsl.dimensions.length ? `grouped by ${dsl.dimensions.join(', ')}` : 'all eligible records'].join(' · ')
}

export function GuidedExplorePage({ planTier, authState }: { planTier: string; authState: 'anonymous' | 'authenticated' }) {
  const initial = guidedQuestionById(new URLSearchParams(window.location.search).get('question')); const [active, setActive] = useState(initial); const [dsl, setDsl] = useState<SemanticDSL>(() => decodeQueryState(window.location.search, initial.dsl)); const query = useSemanticQuery(dsl)
  const data = useMemo(() => resultData(query.data?.data), [query.data]); const suppressed = query.data?.applied_policy.find(item => item.code === 'minimum_cohort')?.message; const locked = !active.eligibleTiers.includes(planTier as PlanTier)
  useEffect(() => { const params = new URLSearchParams({ question: active.id, q: JSON.stringify(dsl) }); window.history.replaceState(null, '', `${window.location.pathname}?${params}`) }, [active.id, dsl])
  const select = (id: string) => { const next = guidedQuestionById(id); setActive(next); setDsl(next.dsl); void track('guided_question_selected', { guided_question_id: next.id, auth_state: authState, plan_tier: planTier, source_surface: 'guided_explore' }) }
  const takeaway = active.summaryTemplate.replace('{leader}', data[0]?.name ?? 'The leading eligible cohort').replace('{value}', data[0] ? String(data[0].value) : 'not yet available')
  const stateMessage = query.isLoading ? 'Reading the governed materialisation…' : query.isError ? 'The takeaway is unavailable until the governed result returns.' : data.length ? takeaway : suppressed ? 'This cohort is protected because it is too small to show.' : 'No eligible result is available for this cohort.'
  return <><header className="page-head guided-head"><p className="eyebrow">Explore insights · guided questions v1.0</p><h1>Start with a useful question.</h1><p>See an evidence-backed result before configuring the model. Full controls and query detail remain one action away.</p></header><nav className="question-grid" aria-label="Guided questions">{guidedQuestions.map(item => <button key={item.id} className={item.id === active.id ? 'active' : ''} onClick={() => select(item.id)} aria-pressed={item.id === active.id}><span>{item.category}</span><strong>{item.question}</strong>{!item.eligibleTiers.includes(planTier as PlanTier) && <small>Pro question</small>}</button>)}</nav><section className="guided-result" aria-labelledby="active-question"><div className="guided-story"><p className="eyebrow">Current question</p><h2 id="active-question">{active.question}</h2><p className="cohort-label"><strong>Current cohort:</strong> {cohortLabel(dsl)}</p>{locked ? <div className="locked-message"><strong>This question needs Pro access.</strong><p>The governed company-level result stays protected. Public questions remain available above.</p><a href="/pricing">Compare plans →</a></div> : <>{query.isError && <p className="preview-notice" role="alert"><strong>The governed result could not be loaded.</strong> Try again or open the detailed view; no preview values are substituted here.</p>}<div className="takeaway"><span>Key takeaway</span><strong>{stateMessage}</strong></div><h3>Why this matters</h3><p>{active.explanation}</p></>}<div className="insight-links"><a href={active.destination}>Open the detailed view →</a><a href="/methodology" onClick={() => void track('learn_explanation_opened', { guided_question_id: active.id, source_surface: 'guided_explore' })}>Methodology and sources →</a></div></div><RankedBar title={active.question} data={locked || query.isError ? [] : data} loading={!locked && query.isLoading} suppressed={locked ? 'Upgrade to view this governed company-level question.' : suppressed}/></section><details className="refine-drawer" onToggle={event => { if (event.currentTarget.open) void track('guided_filter_opened', { guided_question_id: active.id, source_surface: 'guided_explore' }) }}><summary>Refine this view</summary><p>Advanced controls update this result and its shareable URL.</p><SmartFilters dsl={dsl} onChange={setDsl}/><details><summary>View query details</summary><pre>{JSON.stringify(dsl, null, 2)}</pre></details></details>{!locked && <AskFollowUp baseDsl={dsl} suggestions={active.followUps} questionId={active.id}/>}<p className="expert-bypass"><a href={`/ask?${new URLSearchParams({ q: JSON.stringify(dsl) })}`}>Open the full Ask BRSR Lens workspace →</a></p></>
}
