import { useEffect, useMemo, useState } from 'react'

import { Distribution, Heatmap, PercentilePill, RankedBar, ScoreBadge, Timeseries, type ChartDatum } from '../charts/ChartKit'
import { accessToken } from '../lib/auth'
import { apiUrl } from '../lib/api'
import { consolidatePolicyNotices, decodeQueryState, replaceQueryState, type SemanticDSL, useSemanticQuery } from '../lib/semantic'
import { track } from '../lib/track'
import { tokens } from '../theme/tokens'
import { LineageViewer } from './LineageViewer'

const sectorDSL: SemanticDSL = { measures: ['completeness'], dimensions: ['sector'], filters: [{ dimension: 'fy', operator: 'eq', value: 2025 }], shape: 'distribution', sort: { by: 'value', direction: 'desc' }, limit: 20 }
const fallback: ChartDatum[] = [{ name: 'Energy', value: 78 }, { name: 'Metals', value: 71 }, { name: 'Automotive', value: 67 }, { name: 'Healthcare', value: 61 }, { name: 'Consumer', value: 57 }, { name: 'Materials', value: 52 }]

function useDashboard(initial: SemanticDSL) {
  const [dsl, setDsl] = useState(() => decodeQueryState(window.location.search, initial)); const result = useSemanticQuery(dsl)
  useEffect(() => replaceQueryState(dsl), [dsl])
  const data = useMemo(() => result.data?.data?.filter(row => row.value !== null).map((row, index) => ({ name: String(row.company ?? row.sector ?? row.fy ?? `Cohort ${index + 1}`), value: Number(row.value), lineageKey: row.lineage_key ? String(row.lineage_key) : undefined })) ?? fallback, [result.data])
  return { dsl, setDsl, query: result, data }
}

export function SmartFilters({ dsl, onChange }: { dsl: SemanticDSL; onChange: (next: SemanticDSL) => void }) {
  const fy = dsl.filters.find(item => item.dimension === 'fy')?.value ?? 2025
  return <div className="filter-bar"><span className="filter-title">Refine the lens</span><label>Financial year<select value={String(fy)} onChange={event => onChange({ ...dsl, filters: [...dsl.filters.filter(item => item.dimension !== 'fy'), { dimension: 'fy', operator: 'eq', value: Number(event.target.value) }] })}><option>2025</option><option>2024</option></select></label>
    <label>Market cap<select onChange={event => onChange({ ...dsl, filters: [...dsl.filters.filter(item => item.dimension !== 'mcap_band'), ...(event.target.value ? [{ dimension: 'mcap_band', operator: 'eq' as const, value: event.target.value }] : [])] })}><option value="">All bands</option><option value="large">Large</option><option value="mid">Mid</option><option value="small">Small</option></select></label>
    <div className="filter-chips">{dsl.filters.map(item => <span key={item.dimension}>{item.dimension}: {String(item.value)}</span>)}</div></div>
}

function Policy({ notices }: { notices?: Array<{ code: string; message: string }> }) {
  const unique = consolidatePolicyNotices(notices)
  if (!unique.length) return null
  const labels: Record<string, string> = { minimum_cohort: 'Cohort protection', tier_gated: 'Plan access', company_detail_gated: 'Company detail', bottom_ranking_anonymised: 'Responsible ranking' }
  return <aside className="policy-note"><strong>Why some results are not shown</strong>{unique.map(item => <p key={item.code}><span>{labels[item.code] ?? item.code.replaceAll('_', ' ')}</span>{item.message}</p>)}</aside>
}

export function HomePage() {
  const { data, query } = useDashboard(sectorDSL)
  return <><section className="hero"><div><p className="eyebrow">India’s governed BRSR intelligence layer</p><h1>See the substance behind sustainability reporting.</h1><p className="lede">Compare disclosures without losing the page, passage, policy, or method behind a single number.</p><div className="hero-actions"><a className="primary" href="/sectors">Explore sector scorecards</a><a href="/methodology">Read the methodology</a></div></div><div className="headline-stat"><span>Seed corpus · FY25</span><strong>{data[0]?.value.toFixed(0) ?? '—'}</strong><p>leading-sector completeness score</p><small>{query.isError ? 'Preview data · API unavailable' : 'Governed materialisation'}</small></div></section>
    <section className="sector-tiles"><header><p className="eyebrow">The reporting landscape</p><h2>Six sectors. One comparable lens.</h2></header>{data.map((item, index) => <a href={`/sectors?sector=${item.name}`} key={item.name}><span>0{index + 1}</span><h3>{item.name}</h3><strong>{item.value.toFixed(0)}</strong><small>completeness</small></a>)}</section></>
}

export function SectorPage() {
  const { dsl, setDsl, query, data } = useDashboard(sectorDSL); const [pin, setPin] = useState<string | null>(null)
  const suppressed = query.data?.applied_policy.find(item => item.code === 'minimum_cohort')?.message
  return <><PageHead eyebrow="Public intelligence" title="Sector scorecards" copy="What gets disclosed, how substantive it is, and where the leaders are moving."/><SmartFilters dsl={dsl} onChange={setDsl}/><Policy notices={query.data?.applied_policy}/><div className="dashboard-grid"><Distribution title="Completeness distribution" data={data} loading={query.isLoading} suppressed={suppressed}/><RankedBar title="Top-performer spotlight" data={[...data].reverse()} loading={query.isLoading} suppressed={suppressed} onLineage={setPin}/><Timeseries title="Year-on-year movement" data={[{ name: 'FY22', value: 48 }, { name: 'FY23', value: 56 }, { name: 'FY24', value: 64 }, { name: 'FY25', value: 71 }]}/><InsightPanel/></div><LineageViewer pin={pin} onClose={() => setPin(null)}/></>
}

export function CompanyPage() {
  const dsl: SemanticDSL = { measures: ['completeness'], dimensions: ['company'], filters: [{ dimension: 'fy', operator: 'eq', value: 2025 }], shape: 'ranking', sort: { by: 'value', direction: 'desc' }, limit: 10 }
  const dashboard = useDashboard(dsl); const [pin, setPin] = useState<string | null>(null)
  useEffect(() => { void track('viewed_company', { company: new URLSearchParams(location.search).get('company') ?? 'leader' }); void track('viewed_gap_panel', { company: new URLSearchParams(location.search).get('company') ?? 'leader', query: dashboard.dsl }) }, [dashboard.dsl])
  return <><PageHead eyebrow="Pro deep-dive" title="Company disclosure anatomy" copy="History, peer position, score construction, and the clearest route to the leader."/><div className="score-row"><ScoreBadge label="Completeness" value={74}/><ScoreBadge label="Substance" value={68}/><ScoreBadge label="Assurance" value={59}/><div className="percentile-card"><span>Peer position</span><PercentilePill value={87}/><p>13 points above sector median</p></div></div><div className="dashboard-grid"><Timeseries title="KPI history · energy intensity" data={[{ name: 'FY22', value: 92 }, { name: 'FY23', value: 83 }, { name: 'FY24', value: 77 }, { name: 'FY25', value: 69 }]} onLineage={setPin}/><RankedBar title="Peer position" data={dashboard.data} marker={dashboard.data[2]?.name}/><GapPanel/><Waterfall/></div><LineageViewer pin={pin} onClose={() => setPin(null)}/></>
}

export function BenchmarksPage() {
  const dashboard = useDashboard({ ...sectorDSL, dimensions: ['company'], shape: 'ranking' })
  const exportPdf = async () => { const response = await fetch(`${apiUrl}/api/exports/peer-board`, { method: 'POST', headers: { 'Content-Type': 'application/json', ...(accessToken() ? { Authorization: `Bearer ${accessToken()}` } : {}) }, body: JSON.stringify(dashboard.dsl) }); if (!response.ok) { window.location.href = '/pricing'; return } const url = URL.createObjectURL(await response.blob()); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'brsrlens-peer-board.pdf'; anchor.click(); URL.revokeObjectURL(url); await track('export_generated', { kind: 'board-pdf', query: dashboard.dsl }) }
  return <><PageHead eyebrow="Pro workspace" title="Peer benchmarking studio" copy="Build a defensible peer set and export a board-ready comparison."/><SmartFilters dsl={dashboard.dsl} onChange={dashboard.setDsl}/><div className="studio-toolbar"><span>Peer set · Sector + market cap</span><button onClick={() => void exportPdf()}>Export board PDF ↗</button></div><div className="dashboard-grid"><RankedBar title="Completeness slope · peer set" data={dashboard.data}/><Radar/><InsightPanel/></div></>
}

export function MaterialityPage() { const data = ['Energy', 'Water', 'Emissions', 'Waste', 'Workforce', 'Human rights'].map((name, i) => ({ name, value: 92 - i * 11 })); return <><PageHead eyebrow="Public landscape" title="Materiality map" copy="Where Core requirements meet actual disclosure—and where ritual language outruns evidence."/><div className="dashboard-grid"><Heatmap title="Sector × Core topic disclosure density" data={data}/><div className="editorial-panel"><p className="eyebrow">Ritual disclosure watch</p><h3>Policy language is not performance evidence.</h3><p>High phrase reuse and low quantified coverage trigger a visible ritual-disclosure flag. It is a screening signal, not an allegation.</p><div className="legend"><i style={{ background: tokens.color.coral }}/><span>High boilerplate / low evidence</span></div></div></div></> }

export function AssurancePage() { return <><PageHead eyebrow="Public tracker" title="Assurance adoption" copy="Independent assurance adoption, level mix, and sector spread—without overstating small cohorts."/><div className="score-row"><ScoreBadge label="Adoption" value={42}/><ScoreBadge label="Limited level" value={68}/><ScoreBadge label="Reasonable level" value={11}/></div><div className="dashboard-grid"><RankedBar title="Adoption by sector" data={fallback}/><Distribution title="Assurance-readiness distribution" data={fallback}/><div className="locked-panel"><span>Research detail</span><h3>Provider-level spread</h3><p>Provider identity and concentration analysis are available on the Research plan.</p><a href="/pricing">Compare plans →</a></div></div></> }

function PageHead({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <header className="page-head"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{copy}</p></header> }
function InsightPanel() { return <article className="editorial-panel"><p className="eyebrow">What leaders do</p><h3>Connect targets to operating decisions.</h3><p>Leading disclosures name the boundary, baseline, accountable owner, and the decision changed by the metric.</p><a href="/library">Open the Learning Library →</a></article> }
function GapPanel() { return <article className="gap-panel"><p className="eyebrow">Gap to leader</p><h3>Three disclosures would close half the gap.</h3><ol><li>Scope 3 category-level boundary</li><li>Water-stress site exposure</li><li>Assurance scope and exceptions</li></ol><button>Build an action brief</button></article> }
function Waterfall() { return <article className="waterfall"><h3>Score components</h3>{[['Core coverage', 38], ['Evidence quality', 24], ['Specificity', 17], ['Boilerplate', -11]].map(([name, value]) => <div key={name}><span>{name}</span><i style={{ width: `${Math.abs(Number(value)) * 2}%`, background: Number(value) < 0 ? tokens.color.coral : tokens.color.pine }}/><strong>{Number(value) > 0 ? '+' : ''}{value}</strong></div>)}</article> }
function Radar() { return <article className="radar-placeholder"><div/><span>Completeness</span><span>Substance</span><span>Assurance</span><strong>Your company</strong></article> }

export function StyleguidePage() { return <><PageHead eyebrow="Internal reference" title="BRSR Lens visual language" copy="Institutional enough to trust; curious enough to explore."/><section className="style-grid"><article><h3>Colour</h3><div className="swatches">{tokens.categorical.map(color => <i key={color} style={{ background: color }} title={color}/>)}</div></article><article><h3>Typography</h3><h1>Editorial display</h1><p>Data sans keeps dense evidence legible.</p></article><ScoreBadge label="Substance" value={72}/><article className="chart-state suppressed"><strong>Cohort protected</strong><span>Cohort too small to show. Minimum n = 8.</span></article></section><div className="dashboard-grid"><RankedBar title="Ranked bar · populated" data={fallback}/><RankedBar title="Ranked bar · loading" loading/><RankedBar title="Ranked bar · suppressed" suppressed="Cohort too small to show. This protects company anonymity."/></div></> }

interface NLQAnswer { dsl?: SemanticDSL; interpretation: string; confidence: number; unresolved_terms: Array<{ term: string; choices: string[] }>; result?: { data: Array<Record<string, unknown>>; applied_policy: Array<{ code: string; message: string }> }; suggested_refinements: string[]; refusal?: string }
export function AskPage() {
  const [question, setQuestion] = useState('Compare average disclosure completeness by sector for FY 2025.'); const [answer, setAnswer] = useState<NLQAnswer | null>(null); const [running, setRunning] = useState(false)
  const ask = async () => { setRunning(true); await track('nlq_asked', { question_length: question.length }); const response = await fetch(`${apiUrl}/api/nlq`, { method: 'POST', headers: { 'Content-Type': 'application/json', ...(accessToken() ? { Authorization: `Bearer ${accessToken()}` } : {}) }, body: JSON.stringify({ question }) }); setAnswer(await response.json() as NLQAnswer); setRunning(false) }
  const rows = answer?.result?.data.map((row, i) => ({ name: String(row.sector ?? `Cohort ${i + 1}`), value: Number(row.value ?? 0) })) ?? []
  return <><PageHead eyebrow="Ask the corpus" title="A question in. A governed query out." copy="Natural language changes the interface—not the policy, source tables, or suppression rules."/><section className="ask-box"><textarea value={question} onChange={event => setQuestion(event.target.value)} aria-label="Question"/><button onClick={() => void ask()} disabled={running}>{running ? 'Interpreting…' : 'Ask BRSR Lens →'}</button></section>{answer && <section className="transparency"><p className="eyebrow">What I ran · confidence {(answer.confidence * 100).toFixed(0)}%</p><h2>{answer.interpretation}</h2>{answer.refusal && <p className="refusal">{answer.refusal}</p>}<div className="filter-chips">{answer.dsl?.measures.map(item => <span key={item}>{item}</span>)}{answer.dsl?.filters.map(item => <button key={item.dimension}>{item.dimension}: {String(item.value)}</button>)}</div>{answer.unresolved_terms.map(item => <div key={item.term}><strong>By “{item.term}”, did you mean:</strong>{item.choices.map(choice => <button key={choice}>{choice}</button>)}</div>)}{answer.dsl && <button className="text-button" onClick={() => { window.history.pushState(null, '', `/sectors?${new URLSearchParams({ q: JSON.stringify(answer.dsl) })}`) }}>Save as shareable view ↗</button>}<Policy notices={answer.result?.applied_policy}/></section>}{rows.length > 0 && <RankedBar title="Answer" data={rows}/>}</>
}

interface Methodology { method_version: string; minimum_cohort_size: number; coverage: Array<{ principle: string; fields: number }>; changelog: Array<{ version: string; summary: string }>; correction_sla: string }
export function MethodologyPage() {
  const [data, setData] = useState<Methodology | null>(null); useEffect(() => { void fetch(`${apiUrl}/api/methodology`).then(r => r.json() as Promise<Methodology>).then(setData) }, [])
  const cite = () => void navigator.clipboard?.writeText(`BRSR Lens. “Methodology v${data?.method_version ?? '1.0.0'}.” ${location.href} (accessed ${new Date().toLocaleDateString('en-IN')}).`)
  const fieldCount = data?.coverage.reduce((total, item) => total + item.fields, 0) ?? 300
  return <><PageHead eyebrow="Public methodology" title="How every score earns its place." copy="Definitions, coverage, cohort protection, versioning, and corrections—written for scrutiny."/><section className="method-grid"><article><span>01</span><h2>Pinned evidence only</h2><p>Public materialisations use the QA-passed field version pin, never a raw extraction candidate.</p></article><article><span>02</span><h2>Explainable components</h2><p>Completeness, substance and assurance readiness preserve their method version and component ledger.</p></article><article><span>03</span><h2>Cohort protection</h2><p>Sector aggregates are suppressed below n = {data?.minimum_cohort_size ?? 8}. Lower performers are discussed as cohorts.</p></article></section><section className="coverage"><div><p className="eyebrow">Schema coverage</p><h2>{fieldCount} governed BRSR fields</h2></div>{data?.coverage.map(item => <div key={item.principle}><strong>{item.principle}</strong><span>{item.fields} fields</span></div>)}</section><aside className="sla"><strong>Correction commitment</strong><p>{data?.correction_sla ?? 'Reports are acknowledged within five business days.'}</p></aside><button onClick={cite}>Copy formatted citation ↗</button><p className="version">Current method v{data?.method_version ?? '1.0.0'} · Changelog is permanent and versioned.</p></>
}

interface LibraryResult { access: string; items: Array<{ id: string; title: string; topic: string; pattern_note: string }> }
export function LibraryPage() { const [query, setQuery] = useState(''); const [data, setData] = useState<LibraryResult>({ access: 'teaser', items: [] }); const search = async () => setData(await fetch(`${apiUrl}/api/library?q=${encodeURIComponent(query)}`, { headers: accessToken() ? { Authorization: `Bearer ${accessToken()}` } : {} }).then(r => r.json()) as LibraryResult); useEffect(() => { void fetch(`${apiUrl}/api/library`).then(r => r.json() as Promise<LibraryResult>).then(setData) }, []); return <><PageHead eyebrow="Learning Library" title="Patterns worth learning from." copy="Anonymised by default, grounded in filing excerpts, curated for practical reuse."/><div className="library-search"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="How do leaders describe Scope 3 methodology?"/><button onClick={() => void search()}>Search evidence</button></div><div className="library-grid">{data.items.length ? data.items.map(item => <article key={item.id}><span>{item.topic}</span><h3>{item.title}</h3><p>{item.pattern_note}</p><a href="/pricing">{data.access === 'full' ? 'Read cited exemplar' : 'Unlock full pattern'} →</a></article>) : <article><span>Scope 3</span><h3>Boundary before ambition</h3><p>Strong disclosures identify included categories, estimation coverage, exclusions, and their decision rule before presenting a target.</p><a href="/pricing">Unlock cited exemplar →</a></article>}</div></> }

export function PricingPage() { useEffect(() => { void track('pricing_viewed') }, []); return <><PageHead eyebrow="Simple access" title="Start public. Go deeper when the work demands it." copy="Every tier inherits the same governed definitions and suppression policy."/><div className="pricing-grid">{[['Explore', 'Free', 'Sector scorecards, materiality and methodology'], ['Pro', '₹36,000 / year', 'Company deep-dives, peer studio and full library'], ['Research', 'Talk to us', 'Provider detail, bulk access and research workflows']].map(([name, price, copy]) => <article key={name}><span>{name}</span><h2>{price}</h2><p>{copy}</p><button>{name === 'Explore' ? 'Create free account' : 'Choose plan'} →</button></article>)}</div></> }
