import { useEffect, useMemo, useState } from 'react'

import { apiUrl } from '../lib/api'
import { createFiling, decideProposal, generateExports, getFiling, getFilings, getSchema, mapSection, saveAnswer, uploadDocument, type FilingState, type StudioField } from '../lib/studio'

export function StudioPage({ orgId }: { orgId?: string }) {
  const [schema, setSchema] = useState<StudioField[]>([]); const [filing, setFiling] = useState<FilingState>(); const [principle, setPrinciple] = useState('A'); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false)
  const refresh = async (id: string) => { if (orgId) setFiling(await getFiling(orgId,id)) }
  useEffect(() => { if (!orgId) return; void Promise.all([getSchema(orgId),getFilings(orgId)]).then(async ([form,list]) => { setSchema(form.fields); let id=list.items[0]?.id; if(!id) id=(await createFiling(orgId,new Date().getFullYear())).id; setFiling(await getFiling(orgId,id)) }).catch(error=>setNotice(String(error)) ) }, [orgId])
  const fields = useMemo(()=>schema.filter(field=>field.principle===principle).slice(0,80),[schema,principle])
  if (!orgId) return <section className="page-head"><p className="eyebrow">Filing Studio</p><h1>Sign in with a Studio organisation.</h1><p>The seeded local account is demo+studio@brsrlens.local with password DemoPassword123!.</p></section>
  if (!filing) return <div className="chart-state shimmer">Loading the questionnaire… {notice}</div>
  const reload=()=>refresh(filing.id)
  return <div className="studio"><header className="studio-head"><div><p className="eyebrow">Filing Studio · FY {filing.fy}</p><h1>Prepare, evidence, review.</h1><p>AI drafts are kept outside completion until a person accepts them.</p></div><div className="studio-score"><span>Overall</span><strong>{filing.progress.overall_pct}%</strong><span>Core</span><strong>{filing.progress.core_pct}%</strong></div></header>
    <div className="studio-toolbar"><span>{filing.status} · schema 1.0.0</span><label className="upload">Upload evidence<input type="file" accept=".pdf,.docx,.xlsx" onChange={async event=>{const file=event.target.files?.[0];if(file){setBusy(true);await uploadDocument(orgId,filing.id,file);setNotice(`${file.name} uploaded`);setBusy(false)}}}/></label><button disabled={busy} onClick={async()=>{setBusy(true);const out=await generateExports(orgId,filing.id);setNotice(out.items.map(item=>`${item.kind}: ${item.status}`).join(' · '));setBusy(false)}}>Generate export package</button></div>
    {notice&&<div className="policy-note">{notice}</div>}
    <div className="studio-layout"><aside className="section-nav"><h2>Sections</h2>{Object.entries(filing.progress.sections).map(([key,pct])=><button key={key} className={principle===key?'active':''} onClick={()=>setPrinciple(key)}><i style={{background:`conic-gradient(#174f3d ${pct}%,#ddd ${pct}%)`}}/>{key}<span>{pct}%</span></button>)}</aside>
      <section className="questionnaire"><header><div><p className="eyebrow">{principle}</p><h2>{principle==='A'?'General disclosures':principle==='B'?'Management and policy matrix':`Principle ${principle.replace('P','')}`}</h2></div><button onClick={async()=>{const section=fields[0]?.section;if(section){setBusy(true);await mapSection(orgId,filing.id,section);await reload();setBusy(false)}}}>Draft from documents</button></header>
        {fields.map(field=><FieldInput key={field.field_key} field={field} initial={filing.answers[field.field_key]??''} onSave={async value=>{await saveAnswer(orgId,filing.id,field,value);await reload()}} finding={filing.findings.find(item=>item.field_key===field.field_key)?.message}/>)}</section>
      <aside className="review-lane"><h2>AI proposals</h2>{filing.proposals.filter(item=>item.review_status==='unreviewed').map(item=><article key={item.id}><span>{Math.round(item.confidence*100)}% confidence</span><h3>{item.field_key}</h3><p>{item.value}</p><blockquote>{item.evidence.quote}</blockquote><small>Document page {item.evidence.page}</small><div><button onClick={async()=>{await decideProposal(orgId,filing.id,item.id,'accepted');await reload()}}>Accept</button><button onClick={async()=>{await decideProposal(orgId,filing.id,item.id,'rejected');await reload()}}>Reject</button></div></article>)}{!filing.proposals.some(item=>item.review_status==='unreviewed')&&<p className="empty">Upload documents and draft a section to see evidence-backed proposals.</p>}<h2>Findings</h2>{filing.findings.slice(0,12).map((item,index)=><a key={`${item.field_key}-${index}`} href={`#${item.field_key}`}>{item.severity} · {item.message}</a>)}</aside></div>
    <div className="export-note">Downloads appear in export history through the API at <code>{apiUrl}/api/studio/filings/{filing.id}/exports</code>. Submission remains the company’s responsibility.</div>
  </div>
}

function FieldInput({field,initial,onSave,finding}:{field:StudioField;initial:string;onSave:(value:string)=>Promise<void>;finding?:string}){const [value,setValue]=useState(initial);useEffect(()=>setValue(initial),[initial]);const common={id:field.field_key,value,onChange:(event:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setValue(event.target.value),onBlur:()=>{if(value&&value!==initial)void onSave(value)}};return <div className={`studio-field ${finding?'has-finding':''}`}><label htmlFor={field.field_key}>{field.label}{field.core_kpi&&<b>Core</b>}</label><small>{field.field_key}{field.unit&&` · ${field.unit}`}</small>{field.dtype==='boolean'?<select {...common}><option value="">Select</option><option value="true">Yes</option><option value="false">No</option></select>:field.dtype==='text'?<textarea {...common}/>:<input {...common} type={field.dtype==='date'?'date':'number'}/>} {finding&&<p>{finding}</p>}</div>}
