from __future__ import annotations

import html
import io
import zipfile
from typing import Any

import fitz  # type: ignore[import-untyped]

from api.app.db.taxonomy import load_studio_schema
from worker.studio.engine import Finding, progress

SUBMISSION_NOTE = (
    "Submission-preparation note: these files support filing preparation only. The company and its "
    "advisors must review, approve and submit through the applicable exchange portal. "
    "BRSR Lens does "
    "not submit filings and does not assume the reporting entity's statutory liability."
)


def _lines(
    answers: dict[str, str], title: str, status: str, trail: list[dict[str, Any]]
) -> list[str]:
    schema = load_studio_schema()
    catalog = {field["field_key"]: field for field in schema["fields"]}
    lines = [
        title,
        "DRAFT — prepared with BRSR Lens" if status != "final" else "FINAL",
        SUBMISSION_NOTE,
    ]
    current = ""
    for key, value in sorted(
        answers.items(), key=lambda item: (catalog.get(item[0], {}).get("principle", ""), item[0])
    ):
        field = catalog.get(key)
        if not field:
            continue
        if field["principle"] != current:
            current = str(field["principle"])
            lines.append(f"Section {current}")
        lines.append(f"{field['label']}: {value}{' ' + field['unit'] if field.get('unit') else ''}")
    lines.append("Change-log and authorship trail")
    lines.extend(
        f"{item.get('field_key')}: {item.get('author')} · {item.get('review_status')}"
        for item in trail
    )
    return lines


def render_pdf(
    answers: dict[str, str], *, title: str, status: str, trail: list[dict[str, Any]]
) -> bytes:
    document = fitz.open()
    page = document.new_page(width=595, height=842)
    page.draw_rect(fitz.Rect(0, 0, 595, 104), color=(0.09, 0.31, 0.24), fill=(0.09, 0.31, 0.24))
    y = 48.0
    for index, line in enumerate(_lines(answers, title, status, trail)):
        if y > 770:
            page = document.new_page(width=595, height=842)
            page.insert_text(
                (48, 36), "BRSR LENS · FILING DRAFT", fontsize=8, color=(0.09, 0.31, 0.24)
            )
            y = 62
        if index == 0:
            page.insert_textbox(fitz.Rect(48, y, 548, y + 42), line, fontsize=20, color=(1, 1, 1))
            y += 68
            continue
        if line.startswith("Section ") or line == "Change-log and authorship trail":
            page.draw_rect(
                fitz.Rect(48, y - 12, 548, y + 14),
                color=(0.9, 0.93, 0.91),
                fill=(0.9, 0.93, 0.91),
            )
            page.insert_text((56, y + 4), line, fontsize=12, color=(0.09, 0.31, 0.24))
            y += 32
            continue
        color = (0.55, 0.22, 0.19) if index == 1 else (0.12, 0.16, 0.14)
        page.insert_textbox(fitz.Rect(48, y, 548, y + 38), line, fontsize=9, color=color)
        y += 28 if index == 2 else 20
    for page_number, output_page in enumerate(document, start=1):
        output_page.draw_line((48, 806), (548, 806), color=(0.82, 0.8, 0.74), width=0.5)
        output_page.insert_text(
            (48, 822), "Generated by BRSR Lens · evidence remains attached", fontsize=7
        )
        output_page.insert_text((525, 822), str(page_number), fontsize=7)
    return bytes(document.tobytes())


def render_docx(
    answers: dict[str, str], *, title: str, status: str, trail: list[dict[str, Any]]
) -> bytes:
    def paragraph(index: int, line: str) -> str:
        style = (
            "Title"
            if index == 0
            else "Heading1"
            if line.startswith("Section ") or line == "Change-log and authorship trail"
            else "Subtitle"
            if index in {1, 2}
            else "Normal"
        )
        return (
            f'<w:p><w:pPr><w:pStyle w:val="{style}"/></w:pPr>'
            f"<w:r><w:t>{html.escape(line)}</w:t></w:r></w:p>"
        )

    paragraphs = "".join(
        paragraph(index, line) for index, line in enumerate(_lines(answers, title, status, trail))
    )
    document_xml = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
        f'<w:body>{paragraphs}<w:sectPr><w:pgMar w:top="1134" w:right="1134" '
        'w:bottom="1134" w:left="1134"/></w:sectPr></w:body></w:document>'
    )
    styles_xml = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
        '<w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/>'
        '<w:rPr><w:rFonts w:ascii="Aptos"/><w:sz w:val="20"/></w:rPr></w:style>'
        '<w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/>'
        '<w:rPr><w:color w:val="174F3D"/><w:sz w:val="36"/><w:b/></w:rPr></w:style>'
        '<w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="Heading 1"/>'
        '<w:pPr><w:spacing w:before="260" w:after="100"/></w:pPr>'
        '<w:rPr><w:color w:val="174F3D"/><w:sz w:val="28"/><w:b/></w:rPr></w:style>'
        '<w:style w:type="paragraph" w:styleId="Subtitle"><w:name w:val="Subtitle"/>'
        '<w:rPr><w:color w:val="76531E"/><w:i/></w:rPr></w:style></w:styles>'
    )
    content_types = (
        '<?xml version="1.0" encoding="UTF-8"?>'
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.'
        'relationships+xml"/>'
        '<Default Extension="xml" ContentType="application/xml"/>'
        '<Override PartName="/word/document.xml" ContentType="application/vnd.'
        'openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
        '<Override PartName="/word/styles.xml" ContentType="application/vnd.'
        'openxmlformats-officedocument.wordprocessingml.styles+xml"/>'
        "</Types>"
    )
    relationships = (
        '<?xml version="1.0" encoding="UTF-8"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/'
        '2006/relationships/officeDocument" Target="word/document.xml"/>'
        "</Relationships>"
    )
    document_relationships = (
        '<?xml version="1.0" encoding="UTF-8"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rIdStyles" Type="http://schemas.openxmlformats.org/officeDocument/'
        '2006/relationships/styles" Target="styles.xml"/></Relationships>'
    )
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("[Content_Types].xml", content_types)
        archive.writestr("_rels/.rels", relationships)
        archive.writestr("word/document.xml", document_xml)
        archive.writestr("word/styles.xml", styles_xml)
        archive.writestr("word/_rels/document.xml.rels", document_relationships)
    return output.getvalue()


def gap_report_data(
    answers: dict[str, str], findings: list[Finding], answer_meta: dict[str, dict[str, Any]]
) -> dict[str, Any]:
    state = progress(answers, answer_meta)
    evidenced = sum(bool(meta.get("evidence_doc_id")) for meta in answer_meta.values())
    score = max(
        0, round((state["core_pct"] * 0.6) + (min(100, evidenced * 2) * 0.4) - len(findings) * 2)
    )
    priorities = [item.as_dict() for item in findings[:12]]
    agenda = [item["message"] for item in priorities[:5]] or [
        "Complete evidence review and final sign-off"
    ]
    return {
        "score": score,
        "core_coverage_pct": state["core_pct"],
        "evidence_answer_count": evidenced,
        "priorities": priorities,
        "bioedge_page": {
            "title": "How Panacea Bioedge can help",
            "label": "Advisory services — optional",
            "agenda": agenda,
        },
        "submission_note": SUBMISSION_NOTE,
    }


def render_gap_pdf(data: dict[str, Any]) -> bytes:
    document = fitz.open()
    page = document.new_page()
    page.insert_text((48, 64), "Assurance-readiness gap report", fontsize=20)
    page.insert_text((48, 96), f"Readiness score: {data['score']}/100", fontsize=14)
    page.insert_text((48, 122), f"BRSR Core coverage: {data['core_coverage_pct']}%", fontsize=11)
    y = 160
    for item in data["priorities"]:
        page.insert_textbox(
            fitz.Rect(48, y, 540, y + 40), f"• {item['message']} — {item['fix_hint']}", fontsize=9
        )
        y += 36
    page = document.new_page()
    bioedge = data["bioedge_page"]
    page.insert_text((48, 64), str(bioedge["title"]), fontsize=20)
    page.insert_text((48, 90), str(bioedge["label"]), fontsize=10)
    y = 128
    for agenda in bioedge["agenda"]:
        page.insert_textbox(fitz.Rect(48, y, 540, y + 45), f"• {agenda}", fontsize=11)
        y += 40
    page.insert_textbox(fitz.Rect(48, 700, 540, 780), str(data["submission_note"]), fontsize=8)
    return bytes(document.tobytes())
