import type { SemanticDSL } from '../lib/semantic'

export type PlanTier = 'explore' | 'pro' | 'studio' | 'research'

export interface GuidedQuestion {
  id: string
  version: '1.0.0'
  category: 'sector' | 'core' | 'substance' | 'materiality' | 'assurance' | 'environment'
  question: string
  dsl: SemanticDSL
  summaryTemplate: string
  explanation: string
  followUps: Array<{ id: string; question: string }>
  eligibleTiers: PlanTier[]
  destination: string
}

const publicTiers: PlanTier[] = ['explore', 'pro', 'studio', 'research']
const paidTiers: PlanTier[] = ['pro', 'studio', 'research']
export const guidedQuestionsVersion = '1.0.0' as const

export const guidedQuestions: GuidedQuestion[] = [
  { id: 'sector-completeness-fy25', version: guidedQuestionsVersion, category: 'sector', question: 'Which sectors are most complete this year?', dsl: { measures: ['completeness'], dimensions: ['sector'], filters: [{ dimension: 'fy', operator: 'eq', value: 2025 }], shape: 'distribution', sort: { by: 'value', direction: 'desc' }, limit: 20 }, summaryTemplate: '{leader} has the highest average completeness in the eligible FY25 cohort.', explanation: 'Completeness shows whether expected information is present. It does not judge whether the disclosure is specific or independently assured.', followUps: [{ id: 'compare-fy24', question: 'Compare this with FY 2024.' }, { id: 'large-cap-only', question: 'Show only large-cap companies.' }], eligibleTiers: publicTiers, destination: '/sectors' },
  { id: 'substance-by-sector', version: guidedQuestionsVersion, category: 'substance', question: 'Where is disclosure most substantive?', dsl: { measures: ['substance'], dimensions: ['sector'], filters: [{ dimension: 'fy', operator: 'eq', value: 2025 }], shape: 'distribution', sort: { by: 'value', direction: 'desc' }, limit: 20 }, summaryTemplate: '{leader} leads this view on specific, decision-useful disclosure.', explanation: 'Substance rewards specificity, quantified evidence, boundaries, and decision-useful detail; it is distinct from simply filling every field.', followUps: [{ id: 'compare-completeness', question: 'Compare substance with completeness.' }, { id: 'explain-gap', question: 'What can explain the difference?' }], eligibleTiers: publicTiers, destination: '/sectors' },
  { id: 'core-readiness-gaps', version: guidedQuestionsVersion, category: 'core', question: 'Where are BRSR Core readiness gaps most common?', dsl: { measures: ['assurance_readiness'], dimensions: ['sector'], filters: [{ dimension: 'fy', operator: 'eq', value: 2025 }], shape: 'distribution', sort: { by: 'value', direction: 'asc' }, limit: 20 }, summaryTemplate: 'The lowest visible cohort is {leader}; small cohorts remain protected.', explanation: 'Readiness reflects evidence coverage and validation checks. Formal assurance is a separate engagement performed by an independent provider.', followUps: [{ id: 'largest-gaps', question: 'Which evidence gaps drive this view?' }, { id: 'fy24-core', question: 'How did this compare with FY 2024?' }], eligibleTiers: publicTiers, destination: '/materiality' },
  { id: 'materiality-evidence', version: guidedQuestionsVersion, category: 'materiality', question: 'How does materiality evidence vary by sector?', dsl: { measures: ['substance'], dimensions: ['sector'], filters: [{ dimension: 'fy', operator: 'eq', value: 2025 }], shape: 'comparison', sort: { by: 'value', direction: 'desc' }, limit: 20 }, summaryTemplate: '{leader} shows the strongest evidence-linked substance in this cohort.', explanation: 'This is a screening view of disclosure substance, not a judgement that a company selected the right material topics.', followUps: [{ id: 'energy-only', question: 'Focus on the energy sector.' }, { id: 'evidence-patterns', question: 'What does stronger evidence look like?' }], eligibleTiers: publicTiers, destination: '/materiality' },
  { id: 'assurance-trend', version: guidedQuestionsVersion, category: 'assurance', question: 'How is independent assurance adoption changing?', dsl: { measures: ['assurance_readiness'], dimensions: ['fy'], filters: [{ dimension: 'fy', operator: 'between', value: [2024, 2025] }], shape: 'timeseries', sort: { by: 'value', direction: 'asc' }, limit: 10 }, summaryTemplate: 'The latest governed readiness materialisation is {value}.', explanation: 'This guided proxy shows assurance readiness over time. Open Assurance trends for public adoption; readiness must not be read as independent assurance.', followUps: [{ id: 'adoption-detail', question: 'Show assurance adoption by sector.' }, { id: 'levels', question: 'Explain limited and reasonable assurance.' }], eligibleTiers: publicTiers, destination: '/assurance' },
  { id: 'market-cap-quality', version: guidedQuestionsVersion, category: 'sector', question: 'How does reporting quality vary by market-cap band?', dsl: { measures: ['completeness'], dimensions: ['mcap_band'], filters: [{ dimension: 'fy', operator: 'eq', value: 2025 }], shape: 'comparison', sort: { by: 'value', direction: 'desc' }, limit: 10 }, summaryTemplate: '{leader} has the highest average completeness among eligible bands.', explanation: 'Market-cap comparisons describe the available cohort and do not imply that size causes reporting quality.', followUps: [{ id: 'substance-bands', question: 'Compare substance by market-cap band.' }, { id: 'sector-control', question: 'Keep the same band and compare sectors.' }], eligibleTiers: publicTiers, destination: '/sectors' },
  { id: 'company-scope3', version: guidedQuestionsVersion, category: 'substance', question: 'What do leading companies disclose about emissions?', dsl: { measures: ['p6.e3.scope1_tco2e'], dimensions: ['company'], filters: [{ dimension: 'fy', operator: 'eq', value: 2025 }], shape: 'ranking', sort: { by: 'value', direction: 'desc' }, limit: 10 }, summaryTemplate: '{leader} is the highest visible reporter in this governed measure view.', explanation: 'Reported emissions are not a performance ranking. Boundaries, units, estimation methods, and company scale must be considered before comparison.', followUps: [{ id: 'intensity', question: 'Compare emissions intensity instead.' }, { id: 'methodology', question: 'What boundary details should I check?' }], eligibleTiers: paidTiers, destination: '/companies' },
  { id: 'company-energy-fy25', version: guidedQuestionsVersion, category: 'environment', question: 'Which companies report the most energy use?', dsl: { measures: ['p6.e1.energy_total_gj'], dimensions: ['company'], filters: [{ dimension: 'fy', operator: 'eq', value: 2025 }], shape: 'ranking', sort: { by: 'value', direction: 'desc' }, limit: 25 }, summaryTemplate: '{leader} reports the highest converted energy total in this FY25 cohort.', explanation: 'MJ, GJ and TJ are converted to GJ. This is a scale measure, not an efficiency or performance judgement; compare the turnover-normalized view next.', followUps: [{ id: 'energy-intensity', question: 'Normalize this by turnover.' }, { id: 'energy-boundary', question: 'What reporting-boundary caveats apply?' }], eligibleTiers: paidTiers, destination: '/companies' },
  { id: 'company-water-fy25', version: guidedQuestionsVersion, category: 'environment', question: 'Which companies report the most water withdrawal?', dsl: { measures: ['p6.e2.water_total_kl'], dimensions: ['company'], filters: [{ dimension: 'fy', operator: 'eq', value: 2025 }], shape: 'ranking', sort: { by: 'value', direction: 'desc' }, limit: 25 }, summaryTemplate: '{leader} reports the highest water withdrawal in the FY25 cohort.', explanation: 'All values use kL and the entity-wide DCYMain context. A larger total may reflect company scale or sector, not weaker water management.', followUps: [{ id: 'water-intensity', question: 'Normalize this by turnover.' }, { id: 'water-source', question: 'Break withdrawal down by source.' }], eligibleTiers: paidTiers, destination: '/companies' },
  { id: 'company-energy-intensity-fy25', version: guidedQuestionsVersion, category: 'environment', question: 'Which companies use less energy per INR crore turnover?', dsl: { measures: ['normalized.energy_gj_per_inr_crore'], dimensions: ['company'], filters: [{ dimension: 'fy', operator: 'eq', value: 2025 }], shape: 'ranking', sort: { by: 'value', direction: 'asc' }, limit: 25 }, summaryTemplate: '{leader} has the lowest provisional energy intensity in this cohort.', explanation: 'Converted GJ is divided by inferred turnover in INR crore. Turnover scale assumptions are visible and reviewable in Admin; cross-sector comparisons need care.', followUps: [{ id: 'energy-total', question: 'Show total energy instead.' }, { id: 'same-sector', question: 'Keep comparisons within a sector.' }], eligibleTiers: paidTiers, destination: '/companies' },
  { id: 'company-water-intensity-fy25', version: guidedQuestionsVersion, category: 'environment', question: 'Which companies withdraw less water per INR crore turnover?', dsl: { measures: ['normalized.water_kl_per_inr_crore'], dimensions: ['company'], filters: [{ dimension: 'fy', operator: 'eq', value: 2025 }], shape: 'ranking', sort: { by: 'value', direction: 'asc' }, limit: 25 }, summaryTemplate: '{leader} has the lowest provisional water intensity in this cohort.', explanation: 'Water withdrawal in kL is divided by inferred turnover in INR crore. Zero or boundary-limited disclosures require source review before interpretation.', followUps: [{ id: 'water-total', question: 'Show total withdrawal instead.' }, { id: 'same-sector', question: 'Keep comparisons within a sector.' }], eligibleTiers: paidTiers, destination: '/companies' },
  { id: 'company-emissions-intensity-fy25', version: guidedQuestionsVersion, category: 'environment', question: 'Which companies report lower Scope 1+2 emissions intensity?', dsl: { measures: ['normalized.scope12_tco2e_per_inr_crore'], dimensions: ['company'], filters: [{ dimension: 'fy', operator: 'eq', value: 2025 }], shape: 'ranking', sort: { by: 'value', direction: 'asc' }, limit: 25 }, summaryTemplate: '{leader} has the lowest provisional Scope 1+2 intensity in this cohort.', explanation: 'Converted Scope 1+2 tCO2e is divided by inferred turnover in INR crore. Unit and turnover assumptions remain provisional and must be reviewed before external claims.', followUps: [{ id: 'scope-total', question: 'Show absolute emissions instead.' }, { id: 'same-sector', question: 'Keep comparisons within a sector.' }], eligibleTiers: paidTiers, destination: '/companies' },
  { id: 'boilerplate-watch', version: guidedQuestionsVersion, category: 'substance', question: 'What distinguishes substantive disclosure from boilerplate?', dsl: { measures: ['substance'], dimensions: ['sector'], filters: [{ dimension: 'fy', operator: 'eq', value: 2025 }], shape: 'distribution', sort: { by: 'value', direction: 'desc' }, limit: 20 }, summaryTemplate: '{leader} has the strongest average substance signal in the current cohort.', explanation: 'The substance signal screens for specificity and evidence. It is not an allegation about any company and should be read with source lineage.', followUps: [{ id: 'strong-pattern', question: 'Show a strong disclosure pattern.' }, { id: 'weak-pattern', question: 'What signals generic policy language?' }], eligibleTiers: publicTiers, destination: '/library' },
]

export function guidedQuestionById(id: string | null): GuidedQuestion {
  return guidedQuestions.find(item => item.id === id) ?? guidedQuestions[0]
}
