#!/usr/bin/env bash
# Render /opt/brsrlens/env/.env from Parameter Store.
#
# Runs as ExecStartPre of brsrlens.service, so every start picks up rotated
# secrets. Nothing here is written to the image, the AMI or the repository.
#
# Refuses to produce a file while any parameter still holds the CHANGE_ME
# placeholder Terraform created it with: a half-configured start would fail
# later and less legibly, most likely mid-migration.
set -euo pipefail

source /opt/brsrlens/env/node.env

ENV_FILE="${ENV_FILE:-/opt/brsrlens/env/.env}"
TMP_FILE="$(mktemp /opt/brsrlens/env/.env.XXXXXX)"
trap 'rm -f "$TMP_FILE"' EXIT

log() { printf '[render-env] %s\n' "$*"; }

log "reading ${SSM_PREFIX}/env from ${AWS_REGION}"

# get-parameters-by-path paginates at 10 items; --no-paginate would silently
# truncate the configuration, so let the CLI walk every page.
PARAMS_JSON="$(aws ssm get-parameters-by-path \
  --path "${SSM_PREFIX}/env" \
  --with-decryption \
  --recursive \
  --region "${AWS_REGION}" \
  --output json)"

UNSET="$(jq -r '.Parameters[] | select(.Value == "CHANGE_ME") | .Name' <<<"$PARAMS_JSON")"
if [[ -n "$UNSET" ]]; then
  log "refusing to render: these parameters are still placeholders"
  printf '  %s\n' $UNSET
  log "set each with: aws ssm put-parameter --name <name> --type SecureString --overwrite --value ..."
  exit 1
fi

{
  echo "# Generated by render-env.sh at $(date -u +%FT%TZ). Do not edit; edit Parameter Store."
  # Values are written raw, one KEY=value per line, which is the format docker
  # compose --env-file expects. Quoting would become part of the value.
  jq -r '.Parameters[] | "\(.Name | split("/") | last)=\(.Value)"' <<<"$PARAMS_JSON"

  # Node-level facts the stack needs but that are not application settings.
  echo "REGISTRY=${REGISTRY}"
  echo "DOMAIN_NAME=${DOMAIN_NAME}"

  PG_DB="${POSTGRES_DB:-brsrlens}"
  PG_USER="${POSTGRES_USER:-brsrlens}"
  PG_PASSWORD="$(jq -r '.Parameters[] | select(.Name | endswith("/POSTGRES_PASSWORD")) | .Value' <<<"$PARAMS_JSON")"
  echo "POSTGRES_DB=${PG_DB}"
  echo "POSTGRES_USER=${PG_USER}"

  # Built here rather than stored, so the connection string can never disagree
  # with the password Postgres was actually initialised with. @uri escapes the
  # password, which otherwise breaks the URL on characters like / @ : #.
  PG_PASSWORD_ENC="$(jq -rn --arg p "$PG_PASSWORD" '$p|@uri')"
  echo "DATABASE_URL=postgresql+asyncpg://${PG_USER}:${PG_PASSWORD_ENC}@postgres:5432/${PG_DB}"

  # deploy.sh pins the tag it is rolling out. Fall back to the recorded current
  # release so a plain `systemctl restart brsrlens` re-runs the same image
  # rather than drifting to whatever :latest happens to be.
  RELEASE_TAG="${RELEASE_TAG:-$(aws ssm get-parameter --name "${SSM_PREFIX}/release/current" \
    --region "${AWS_REGION}" --query Parameter.Value --output text)}"
  echo "RELEASE_TAG=${RELEASE_TAG}"
} >"$TMP_FILE"

chmod 600 "$TMP_FILE"
mv "$TMP_FILE" "$ENV_FILE"
trap - EXIT

# --- nginx admin allowlist --------------------------------------------------
# Rendered here rather than baked into the web image so the allowlist can change
# without a rebuild. Absent parameter means role-gating only.
mkdir -p /opt/brsrlens/nginx
ALLOW_CIDRS="$(aws ssm get-parameter --name "${SSM_PREFIX}/env/ADMIN_ALLOW_CIDRS" \
  --region "${AWS_REGION}" --query Parameter.Value --output text 2>/dev/null || echo "")"

{
  if [[ -z "$ALLOW_CIDRS" || "$ALLOW_CIDRS" == "None" || "$ALLOW_CIDRS" == "CHANGE_ME" ]]; then
    echo "# ADMIN_ALLOW_CIDRS unset: /admin/* is protected by application role checks alone."
    echo "allow all;"
  else
    echo "# Rendered from ${SSM_PREFIX}/env/ADMIN_ALLOW_CIDRS"
    tr ',' '\n' <<<"$ALLOW_CIDRS" | while read -r cidr; do
      cidr="$(tr -d '[:space:]' <<<"$cidr")"
      [[ -n "$cidr" ]] && echo "allow ${cidr};"
    done
  fi
} >/opt/brsrlens/nginx/admin-allowlist.conf

log "wrote ${ENV_FILE} ($(grep -c '=' "$ENV_FILE") settings) and the admin allowlist"
